server:
  port: 8082
  servlet:
    context-path: /sell


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://144.34.134.100:3306/sell?characterEncoding=utf-8&userSSL=false
    username: hs
    password: 123456




  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  devtools:
    remote:
      restart:
        enabled: true
  #为空非必须字段不返回，需要返回加初始值
  jackson:
    default-property-inclusion: non_null

  freemarker:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379

project-url:
  project: http://127.0.0.1:8082

