server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8


  servlet:
    multipart:
      max-file-size: 1280KB
      max-request-size: 1280KB


  data:
    mongodb:
      uri: mongodb://localhost:27017/test


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://144.34.134.100:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: hs
    password: 123456