server:
  port: 8087
  
spring:
  application:
    name: spring-cloud-consumer
    
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka #,http://peer2:8083/eureka,http://peer3:8084/eureka
      
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}