server:
  port: 8083
  
spring:
  #profiles
  application:
    name: spring-cloud-eureka
    
eureka:
  instance:
    hostname: peer3
    instance-id: ${spring.application.name}:${server.port}
    
  client:
    #是否将自己注册到Eureka Server，默认为true
    #register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true
    #fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    service-url:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/