server:
  address: 127.0.0.1
  port: 8081
  servlet:
    context-path: /jpa
  connection-timeout: 1000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
    