server:
  port: 8083

#elastictsearch服务配置
spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      properties:
        path.home: target/elastic
        transport:
          tcp:
            connect_timeout: 120s

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://144.34.134.100:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: hs
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true